chandler:
    debug: false
    websiteUrl: "http://openvk.duckdns.org:9999"
    rootApp:    "openvk"
    
    preferences:
        appendExtension: "xhtml"
        adminUrl: "/chandlerd"
        exposeChandler: true
        logs:
            enabled: true
            entitiesNamespace: "openvk\\Web\\Models\\Entities\\"
    
    extensions:
        path: null
        allEnabled: false
    
    database:
        dsn: "mysql:host=mariadb-primary-dev;dbname=db_dev"
        user: "openvk"
        password: "openvk_dev"
    
    security:
        secret: "dev_j09y4af9vm86nyid77q6yldp27ud65faxk4xfn5pgnd66duqskw1bpq6gfu425xbrmyz9iv9vzgurdk9c6q2icq9lsdysq8x15f4scd6pmxte4ui6xlr64qjix2gllkl"
        csrfProtection: "permissive"
        extendedValidation: false
        sessionDuration: 14

    email:
        host: "mail.example.com"
        port: 465
        user: "user"
        pass: "word"
        addr: "noreply@example.com"
        ssl: true
